(in-package :backpack)

(defcategory transaction ()
  "Category for logging transactions issues")
(defcategory cache ()
  "Category for logging object's cache issues")
(defcategory mop ()
   "Category for logging mop issues")
(defcategory index ()
  "Category for logging index issues")
(defcategory schema ()
  "Category for logging schema issues")
(defcategory serialize ()
  "Category for logging serialization issues")
(defcategory gc ()
  "Category for logging garbage collection issues")